services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: gamestore
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306:3306"
    volumes:
      - ./.srv/mysql:/var/lib/mysql

  wordpress:
    image: wordpress:6.6.2-php8.2-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: gamestore
    ports:
      - "8000:80"
    volumes:
      - ./.srv/wordpress:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./mu-plugins/:/var/www/html/wp-content/mu-plugins/
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      PMA_PORT: 3306
    ports:
      - "8181:80"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mysql:3306"] 
      interval: 5s
      retries: 5
      start_period: 10s

volumes: {}
